"""empty message

Revision ID: 63aac7e1d58f
Revises: d3417020f84d
Create Date: 2026-04-21 18:18:30.606525
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '63aac7e1d58f'
down_revision = 'd3417020f84d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('supported_actions', sa.String(length=255), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'supported_actions')
    # ### end Alembic commands ###

