"""empty message

Revision ID: d3417020f84d
Revises: efa5b6248e65
Create Date: 2026-04-04 18:27:05.115255
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd3417020f84d'
down_revision = 'efa5b6248e65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'device_id')
    # ### end Alembic commands ###

