"""empty message

Revision ID: efa5b6248e65
Revises: 613d12d45abc
Create Date: 2026-03-27 23:24:57.583890
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'efa5b6248e65'
down_revision = '613d12d45abc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('device_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'device_id')
    # ### end Alembic commands ###

